name: Update openwrt-packages

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

jobs:
  build:
    runs-on: Ubuntu-20.04

    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [main]
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Initialization environment
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ${{matrix.target}}.sh
        git clone -b master https://github.com/kenzok8/openwrt-packages.git ${{matrix.target}}
        cd ${{matrix.target}}
        $GITHUB_WORKSPACE/${{matrix.target}}.sh
        $GITHUB_WORKSPACE/Modify.sh
        
    - name: Upload
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      run: |
        [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}
        [ -e $GITHUB_WORKSPACE/README.md ] && cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/${{matrix.target}}
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git add .
        git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
        git push --force "https://${{ secrets.ACCESS_TOKEN }}@github.com/kenzok8/openwrt-packages.git"        
        
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 0
